stages:          # List of stages for jobs, and their order of execution
  - tags

tags-job:       # This job runs in the build stage, which runs first.
  stage: tags
  tags:
   - tagging
  script:
    - echo "Tagging automation process..."
    - echo "$PAT_REPO_URL"
    - git status
    - git branch -l --all
    - git describe --tags --abbrev=0 2>/dev/null
    - git rev-parse HEAD
    - ./config.sh --oscam-revision
    - ./config.sh --oscam-commit
    
    - sha=$(git rev-parse HEAD)
    - curr_tag=$(git describe --tags --abbrev=0 2>/dev/null)
    - new_tag=$(( $curr_tag + 10 ))

    - echo "Removing existing tag:$new_tag..."
    - if git tag --list | grep -iq "$new_tag"; then
        git tag --delete "$new_tag";
      fi;
#        git push "$PAT_REPO_URL" --delete "$new_tag" -o ci.skip;

    - echo "Creating new tag:$new_tag on sha:$sha..."
    - git config user.name "pipeline-user"
    - git config user.email "pipeline-user@$users.noreply.git.streamboard.tv"
    - git tag "$new_tag" "$sha"
#    - git push "$PAT_REPO_URL" "$new_tag" -o ci.skip
    - echo "Tagging automation complete."
